#!/usr/bin/env python3
"""0.0.5 tzdb size spike -- THROWAWAY (P-28).  Emits ONE `.npk` file holding
`ZONE_MODEL.md` Z-7's four flat tables plus the two pools, from tzdata 2026c's
compiled TZif files, so the compiled size can be MEASURED instead of estimated.

This is NOT `tools/gen_tzdb.py`.  It is correct about shape and volume and
deliberately not about content: `ZONE_MODEL.md` Z-12's POSIX footer is captured
but NOT parsed (0.0.5.md §2 step 2), so `posix_rule` is -1 everywhere in the
four-table variant.  A second variant emits POSIX_RULES at the real cardinality
with placeholder contents, because the SIZE question needs the row count and
the row width even where the plan skips the parsing.

    python3 emit.py <out.npk> [--zones N] [--with-posix]
"""
import os, sys, struct
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tzif

HDR = """// GENERATED by meta/scratch/tzdb_spike/emit.py for cycle 0.0.5's size spike.
// THROWAWAY (P-28).  tzdata {ver}.  Shape and volume are real; contents past
// the transition/type/zone tables are not (the POSIX footer is not parsed).
mod:{mod};

pub struct:ZoneTransition = {{ int64:at_utc; int32:type_index; }};
pub struct:ZoneType       = {{ int32:offset_secs; uint8:is_dst; uint16:abbr_offset; }};
pub struct:ZoneEntry      = {{
    uint32:name_offset; uint16:name_len;
    uint32:trans_first; uint16:trans_count;
    uint32:type_first;  uint16:type_count;
    int32:posix_rule;
}};
pub struct:PosixRule = {{
    int32:std_offset_secs;  int32:dst_offset_secs;
    uint16:std_abbr_offset; uint16:dst_abbr_offset;
    uint8:start_month;  uint8:start_week;  uint8:start_dow;  int32:start_secs;
    uint8:end_month;    uint8:end_week;    uint8:end_dow;    int32:end_secs;
    uint8:has_dst;
}};
"""

def build(limit=None):
    zones = tzif.canonical_zones()
    if limit:
        zones = zones[:limit]
    transitions, types, entries = [], [], []
    name_pool = bytearray()
    abbr_pool = bytearray()
    abbr_at = {}
    for z in zones:
        d = tzif.read(os.path.join(tzif.ROOT, z))
        name_off = len(name_pool)
        name_pool += z.encode("ascii")
        t_first, ty_first = len(transitions), len(types)
        for (utoff, isdst, desig) in d["types"]:
            a = d["abbrs"][desig:d["abbrs"].index(b"\x00", desig)].decode("ascii")
            if a not in abbr_at:
                abbr_at[a] = len(abbr_pool)
                abbr_pool += a.encode("ascii") + b"\x00"
            types.append((utoff, 1 if isdst else 0, abbr_at[a]))
        for (at, idx) in d["transitions"]:
            transitions.append((at, idx))
        entries.append({
            "name_offset": name_off, "name_len": len(z),
            "trans_first": t_first, "trans_count": len(d["transitions"]),
            "type_first": ty_first, "type_count": len(d["types"]),
            "footer": d["footer"],
        })
    return zones, transitions, types, entries, bytes(name_pool), bytes(abbr_pool)

def arr(name, ty, rows):
    if not rows:
        return "pub fixed %s[1]:%s = [\n    %s\n];\n" % (ty, name, rows)
    return ("pub fixed %s[%d]:%s = [\n" % (ty, len(rows), name)
            + ",\n".join("    " + r for r in rows) + "\n];\n")

def emit(path, limit=None, with_posix=False):
    mod = os.path.splitext(os.path.basename(path))[0]
    zones, trans, types, entries, npool, apool = build(limit)
    rules = []
    if with_posix:
        # Placeholder rows at the REAL cardinality -- one per zone with a
        # non-empty footer.  Contents are not parsed (0.0.5.md §2 step 2); the
        # question this variant answers is what the table's WIDTH costs.
        for e in entries:
            if e["footer"]:
                e["posix_rule"] = len(rules)
                rules.append("PosixRule{ std_offset_secs: 0i32, dst_offset_secs: 0i32, "
                             "std_abbr_offset: 0u16, dst_abbr_offset: 0u16, "
                             "start_month: 3u8, start_week: 5u8, start_dow: 0u8, start_secs: 3600i32, "
                             "end_month: 10u8, end_week: 5u8, end_dow: 0u8, end_secs: 7200i32, "
                             "has_dst: 1u8 }")
            else:
                e["posix_rule"] = -1
    else:
        for e in entries:
            e["posix_rule"] = -1

    parts = [HDR.format(ver=TZ_VERSION, mod=mod)]
    parts.append(arr("TRANSITIONS", "ZoneTransition",
        ["ZoneTransition{ at_utc: %di64, type_index: %di32 }" % (a, i) for (a, i) in trans]))
    parts.append(arr("TYPES", "ZoneType",
        ["ZoneType{ offset_secs: %di32, is_dst: %du8, abbr_offset: %du16 }" % t for t in types]))
    parts.append(arr("ZONES", "ZoneEntry",
        ["ZoneEntry{ name_offset: %du32, name_len: %du16, trans_first: %du32, "
         "trans_count: %du16, type_first: %du32, type_count: %du16, posix_rule: %di32 }"
         % (e["name_offset"], e["name_len"], e["trans_first"], e["trans_count"],
            e["type_first"], e["type_count"], e["posix_rule"]) for e in entries]))
    parts.append(arr("NAME_POOL", "uint8", ["%du8" % b for b in npool]))
    parts.append(arr("ABBR_POOL", "uint8", ["%du8" % b for b in apool]))
    if with_posix:
        parts.append(arr("POSIX_RULES", "PosixRule", rules))
    parts.append(MAIN.format(
        nz=len(zones), nt=len(trans), nty=len(types),
        npool=len(npool), apool=len(apool),
        nrules=len(rules) if with_posix else 0,
        last_idx=len(trans) - 1, last_at=trans[-1][0],
        swept_text="swept %d\\n" % len(trans),
        swept_len=len("swept %d\n" % len(trans)),
        posix_check=("    if (POSIX_RULES[0].has_dst != 1u8)  {{ exit 26i32; }}\n"
                     "    if (#size_of<PosixRule>() != 32i64) {{ exit 27i32; }}\n"
                     if with_posix else "")))
    src = "".join(parts)
    open(path, "w").write(src)
    return {"zones": len(zones), "transitions": len(trans), "types": len(types),
            "name_pool": len(npool), "abbr_pool": len(apool),
            "posix_rules": len(rules) if with_posix else 0,
            "npk_bytes": len(src.encode())}

TZ_VERSION = tzif.tzdata_version()

MAIN = """
// ===========================================================================
// THE VERDICT HALF.  `npkc` exit 0 is not well-formedness (TM-112), and an
// exhaustive walk that returns early exits 0 exactly like one that ran.  So
// this program declares its domain in the header below, WALKS every row, and
// asserts the count it visited against the declaration -- and only a run that
// passed that assertion reaches the `swept` line, which is why the literal
// number in that line is honest even though it is a compile-time constant.
// ===========================================================================
//
// declared-domain: zones={nz} transitions={nt} types={nty} name_pool={npool} abbr_pool={apool} posix_rules={nrules}
error:EW;

func:main = int32(cstring[]:argv) {{
    // Z-7's cost model multiplies a row WIDTH by a row COUNT.  Every size in
    // ZONE_MODEL.md §3 is wrong if these are wrong, and `#size_of` is measured
    // rather than derived from field widths -- the estimate derived it and got
    // ZoneTransition (12 v 16) and ZoneEntry (16 v 28) wrong.
    if (#size_of<ZoneTransition>() != 16i64) {{ exit 20i32; }}
    if (#size_of<ZoneType>() != 8i64)        {{ exit 21i32; }}
    if (#size_of<ZoneEntry>() != 28i64)      {{ exit 22i32; }}

    // Every zone's transition slice walked, and Z-8's "sorted and strictly
    // increasing" invariant proved PER ZONE -- which is also what proves the
    // rows are really present rather than folded down to the two ends.
    int64:zi = 0i64;
    int64:visited_t = 0i64;
    int64:visited_ty = 0i64;
    while (zi < {nz}i64) {{
        int64:first = (ZONES[zi].trans_first =>! int64);
        int64:n = (ZONES[zi].trans_count =>! int64);
        int64:k = 1i64;
        if (n > 0i64) {{ visited_t = visited_t + 1i64; }}
        while (k < n) {{
            if (TRANSITIONS[first + k].at_utc <= TRANSITIONS[first + k - 1i64].at_utc) {{
                exit 23i32;
            }}
            visited_t = visited_t + 1i64;
            k = k + 1i64;
        }}
        visited_ty = visited_ty + (ZONES[zi].type_count =>! int64);
        zi = zi + 1i64;
    }}
    if (visited_t != {nt}i64)   {{ exit 24i32; }}
    if (visited_ty != {nty}i64) {{ exit 25i32; }}

{posix_check}
    // A row reached through an index the compiler cannot fold: `argv.len` is 1
    // here, so this is the LAST transition -- the access Z-8's binary search
    // actually makes, and the one a constant-folder cannot pre-compute.
    int64:live = ((argv.len =>! int64) - 1i64) + {last_idx}i64;
    if (TRANSITIONS[live].at_utc != {last_at}i64) {{ exit 28i32; }}

    // Both pools walked end to end, so no byte of either can be folded away.
    int64:pi = 0i64; int64:psum = 0i64;
    while (pi < {npool}i64) {{ psum = psum + (NAME_POOL[pi] =>! int64); pi = pi + 1i64; }}
    if (psum < 1i64) {{ exit 29i32; }}
    int64:ai = 0i64; int64:asum = 0i64;
    while (ai < {apool}i64) {{ asum = asum + (ABBR_POOL[ai] =>! int64); ai = ai + 1i64; }}
    if (asum < 1i64) {{ exit 30i32; }}

    cstring:s = to_cstring("{swept_text}") ?! EW;
    int64:w = sys(1i64, 1i64, s.ptr, s.len) ?! EW;
    if (w != {swept_len}i64) {{ exit 31i32; }}
    exit 0i32;
}};

func:failsafe = int32(Error:e) {{
    pick (e) {{
        (EW)             {{ exit 90i32; }},
        (HeapBadRequest) {{ exit 91i32; }},
        (HeapOom)        {{ exit 92i32; }},
        (IntOverflow)    {{ exit 93i32; }},
        (OutOfBounds)    {{ exit 94i32; }},
        (Unreachable)    {{ exit 95i32; }},
        (WildLeak)       {{ exit 96i32; }},
        (*)              {{ exit 99i32; }}
    }}
    exit 9i32;
}};
"""

if __name__ == "__main__":
    out = sys.argv[1]
    limit = None
    with_posix = "--with-posix" in sys.argv
    if "--zones" in sys.argv:
        limit = int(sys.argv[sys.argv.index("--zones") + 1])
    print(emit(out, limit, with_posix))
