#!/usr/bin/env python3
"""Regenerates TRANSCRIPT.txt.  Every command's exit status is captured on its
own line with nothing between, and every status is printed BESIDE the artefact
it should have produced -- because a borrowed 0 is falsified the moment you ask
what it wrote (`../../../../PLAYBOOK.md` §6).  There is no pipeline anywhere in
this file.

    NPKC=... NPKRT=... python3 transcript.py > TRANSCRIPT.txt
"""
import os, subprocess, sys, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
OUT  = os.path.join(REPO, ".internal", "scratch", "0.0.5", "tx")
GEN  = os.path.join(REPO, ".internal", "scratch", "0.0.5", "gen")
NPKC = os.environ["NPKC"]; NPKRT = os.environ["NPKRT"]
TIMEF = os.path.join(OUT, "t.txt")


def say(s=""):
    sys.stdout.write(s + "\n")


def run(cmd, artefact=None, timed=False, cwd=REPO):
    """One command.  Status captured immediately, artefact size beside it."""
    if artefact and os.path.exists(artefact):
        os.remove(artefact)
    full = (["/usr/bin/time", "-o", TIMEF, "-f", "%e %M"] + cmd) if timed else cmd
    r = subprocess.run(full, cwd=cwd, stdout=subprocess.PIPE,
                       stderr=subprocess.STDOUT)
    st = r.returncode
    tail = ""
    if timed:
        w, m = open(TIMEF).read().split()[-2:]
        tail = "   %s s   %s KiB" % (w, m)
    if artefact is None:
        art = ""
    elif os.path.exists(artefact):
        art = "   %s = %d B" % (os.path.relpath(artefact, REPO),
                                os.path.getsize(artefact))
    else:
        art = "   %s = ABSENT" % os.path.relpath(artefact, REPO)
    say("$ " + " ".join(os.path.relpath(c, REPO) if c.startswith("/") and
                        os.path.exists(c) else c for c in cmd))
    say("  exit=%d%s%s" % (st, art, tail))
    out = r.stdout.decode("utf-8", "replace").rstrip()
    for line in (out.splitlines() if out else []):
        if timed and line.strip() and line.strip()[0].isdigit() and len(line.split()) == 2:
            continue
        say("  | " + line)
    return st


def build(stem, src):
    ll = os.path.join(OUT, stem + ".ll")
    obj = os.path.join(OUT, stem + ".o")
    exe = os.path.join(OUT, stem)
    say("--- %s : emitted .npk = %d B" % (stem, os.path.getsize(src)))
    run([NPKC, src, "-o", ll], ll, timed=True)
    run(["llc", "-O0", "-filetype=obj", "-relocation-model=static", ll,
         "-o", obj], obj, timed=True)
    run(["ld.lld", "-static", obj, NPKRT, "-o", exe], exe, timed=True)
    run([exe])
    say()
    return ll, obj, exe


def main():
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(GEN, exist_ok=True)
    say("TRANSCRIPT -- cycle 0.0.5, the tzdb size spike")
    say("=" * 78)
    say("Generated by meta/scratch/tzdb_spike/transcript.py on %s"
        % datetime.date.today().isoformat())
    say("Toolchain: pin aaffb87.  NPKC=%s" % NPKC)
    say("           NPKRT=%s" % NPKRT)
    sys.path.insert(0, HERE)
    import tzif
    ver = tzif.tzdata_version()
    say("Source database: /usr/share/zoneinfo, tzdata %s -- the release" % ver)
    say("           ZONE_MODEL.md Z-4 pins, and the one the estimate it tests")
    say("           was taken from, so the two numbers are comparable.")
    say()
    say("Every exit status below is captured on its own line with nothing "
        "between,")
    say("and printed BESIDE the artefact it should have produced.  No pipeline "
        "is")
    say("used anywhere in the generator.")
    say()

    say("### 0.  The toolchain is the pinned one")
    say("=" * 78)
    run(["sha256sum", NPKC, NPKRT])
    say()

    say("### 1.  COMMISSIONING THE INSTRUMENT, positive and negative")
    say("=" * 78)
    say("A measurement whose instrument was never made to fail is not a")
    say("measurement.  Five zones, then the same file with one row's clock")
    say("wound backwards, then the same file with one zone's `trans_count`")
    say("understated by 3.")
    say()
    small = os.path.join(GEN, "tz_small.npk")
    run([sys.executable, os.path.join(HERE, "emit.py"), small, "--zones", "5"],
        small)
    build("tz_small", small)
    say("  (`swept 101` above equals the domain the header declares.)")
    say()
    run([sys.executable, os.path.join(HERE, "probes.py"), GEN, small])
    say()
    for stem in ("neg_unsorted", "neg_shortsweep"):
        src = os.path.join(GEN, stem + ".npk")
        if os.path.exists(src):
            build(stem, src)
    say("  neg_unsorted   -> exit 23, Z-8's strictly-increasing invariant")
    say("  neg_shortsweep -> exit 24, and NO `swept` line: the walk visited")
    say("                   fewer rows than the header declares.")
    say()

    say("### 2.  THE ROW WIDTHS, measured and not derived")
    say("=" * 78)
    say("`#size_of` is the exit code, so each number is read off the process")
    say("rather than off a comment.  Every candidate is far below 255.")
    say()
    for name in ("ZoneTransition", "ZoneType", "ZoneEntry", "PosixRule"):
        stem = "size_" + name
        src = os.path.join(GEN, stem + ".npk")
        if os.path.exists(src):
            build(stem, src)
    say()

    say("### 3.  THE FULL TABLE -- 447 zones, the four tables and two pools")
    say("=" * 78)
    four = os.path.join(GEN, "tzdb_four.npk")
    run([sys.executable, os.path.join(HERE, "emit.py"), four], four)
    ll4, obj4, exe4 = build("tzdb_four", four)
    say("### 3a. Is it read-only data, or filled in at startup?  (probe 04's")
    say("###     question, at the real scale)")
    run(["grep", "-c", "= constant", ll4])
    run(["grep", "-c", "llvm.global_ctors", ll4])
    say("  (`grep -c` exit 1 means zero matches; the count printed is the")
    say("   artefact, and the two agree.)")
    run(["nm", "-S", "--size-sort", "--radix=d", obj4])
    run(["readelf", "-SW", obj4])
    run(["readelf", "-SW", exe4])
    say()

    say("### 4.  THE SAME, PLUS POSIX_RULES at the real cardinality")
    say("=" * 78)
    five = os.path.join(GEN, "tzdb_five.npk")
    run([sys.executable, os.path.join(HERE, "emit.py"), five, "--with-posix"],
        five)
    ll5, obj5, exe5 = build("tzdb_five", five)
    run(["nm", "-S", "--size-sort", "--radix=d", obj5])
    say()

    say("### 5.  THE BASELINE CONTROL -- the same program, one zone")
    say("=" * 78)
    say("Without it the object size is the program's as well as the tables',")
    say("and the tables' share would be a subtraction nobody checked.")
    say()
    one = os.path.join(GEN, "tzdb_one.npk")
    run([sys.executable, os.path.join(HERE, "emit.py"), one, "--zones", "1"],
        one)
    ll1, obj1, exe1 = build("tzdb_one", one)
    run(["nm", "-S", "--size-sort", "--radix=d", obj1])
    say()
    say("END OF TRANSCRIPT")


if __name__ == "__main__":
    main()
