#!/usr/bin/env python3
"""The civil cross-oracle's corpus -- `meta/specs/CALENDAR.md` C-18,
`meta/specs/TESTING.md` V-6 -- from Python's `datetime` and nothing else.

    python3 tools/gen_civil_oracle.py OUT.npk     write the corpus to OUT.npk
    python3 tools/gen_civil_oracle.py --year Y    print Python's nine fields
                                                  for every day of year Y

WHAT IT WRITES. One row per year `datetime` covers -- `datetime.MINYEAR` to
`datetime.MAXYEAR`, 1 to 9999 -- holding the year, the day number of its
1 January (epoch 1970-01-01 = 0), its length in days, and a DIGEST: the fold
below over nine fields of every one of its days, in date order. Each field is
Python's own answer, read from `datetime` and never computed here:

    year, month, day               `date.fromordinal(o)`
    the day number                 `o - date(1970, 1, 1).toordinal()`
    the weekday, Monday = 1        `isoweekday()`
    the ISO week date's three      `isocalendar()`
    the day of the year            `timetuple().tm_yday`

`tests/unit/sweep/every_oracle_date.npk` computes the same fold from
`src/cal/`'s answers for every day of every year and must equal every row.

THE FOLD. From 0 at each year's first day, for each field value v in turn,
h = (h XOR v) * 1099511628211, both modulo 2**64, v in two's complement; the
digest is h read as a signed 64-bit integer. The multiplier is odd, so each
step is a bijection of h for a fixed v: one wrong value anywhere in a year
changes that year's digest, always. Several wrong values could in principle
cancel; for values that are not chosen to, the chance is about 2**-64.

WHY A DIGEST AND NOT THE ROWS. Every day of years 1 to 9999 is 3 652 059
rows of nine numbers; a digest per year is 9 999 rows and loses nothing a
year's comparison needs. Measured at cycle 0.1.4's planning, rows written out
as a `fixed` table cost about 120 bytes and 0.16 ms of `npkc` each: a few
hundred thousand of them is 33.7 MB and 44 s, and all of them would be about
440 MB. When a year disagrees, the member prints its own nine fields for every
day of that year, and `--year` prints Python's in the same format, so `diff`
names the day and the field.

DETERMINISTIC BY CONSTRUCTION: no clock, no dictionary, no environment, and
nothing about the interpreter in the output -- so the file is a function of
this script and of `datetime`'s answers, and regenerating it is `cmp`-able.
The interpreter it was generated with is recorded where every external
version is, `meta/research/CURRENCY.md`.
"""
import datetime
import sys

MASK = (1 << 64) - 1
PRIME = 1099511628211
EPOCH = datetime.date(1970, 1, 1).toordinal()

HEADER = """\
// GENERATED by `tools/gen_civil_oracle.py` from Python's `datetime`. Do not
// edit it: regenerate it, and `cmp` the result against this file.
//
// THE CIVIL CROSS-ORACLE'S CORPUS -- `meta/specs/CALENDAR.md` C-18,
// `meta/specs/TESTING.md` V-6. One row per year Python's `datetime` covers,
// `datetime.MINYEAR` to `datetime.MAXYEAR`, 1 to 9999:
//
//   year    the year
//   first   the day number of its 1 January, epoch 1970-01-01 = 0:
//           `date(year, 1, 1).toordinal()` less `date(1970, 1, 1).toordinal()`
//   days    its length in days, 365 or 366
//   digest  the fold below, over nine fields of every one of its days in date
//           order: year, month, day, the day number, `isoweekday()`, the three
//           of `isocalendar()`, and `timetuple().tm_yday`
//
// THE FOLD: from 0 at each year's first day, for each field value v in turn,
// h = (h XOR v) * 1099511628211, both modulo 2**64, v in two's complement; the
// digest is h read as a signed 64-bit integer. The multiplier is odd, so one
// wrong value anywhere in a year changes that year's digest.
// `tests/unit/sweep/every_oracle_date.npk` computes the same fold from
// `src/cal/`'s answers and must equal every row.
//
// THE LIMIT, STATED RATHER THAN GLOSSED: Python covers years 1 ... 9999 only,
// so the negative half of the range, -9999 ... 0, has `CALENDAR.md` C-16's
// self-consistency and nothing else.
//
// No `string`, no `buffer`, no container: every field is an `int64`, so
// nothing here owns (`SAFETY.md` S-19b). The interpreter this was generated
// with is `meta/research/CURRENCY.md`'s Python row.
mod:civil_oracle;

pub struct:OracleYear = { int64:year; int64:first; int64:days; int64:digest; };

pub fixed int64:ORACLE_YEARS = {count}i64;

pub fixed OracleYear[{count}]:ORACLE = [
"""


def fields(dt):
    """Python's nine answers for one day, in the fold's order."""
    iy, iw, iwd = dt.isocalendar()
    return (dt.year, dt.month, dt.day, dt.toordinal() - EPOCH,
            dt.isoweekday(), iy, iw, iwd, dt.timetuple().tm_yday)


def year_row(y):
    """(year, first, days, digest) for one year."""
    lo = datetime.date(y, 1, 1).toordinal()
    hi = datetime.date(y, 12, 31).toordinal()
    h = 0
    for o in range(lo, hi + 1):
        for v in fields(datetime.date.fromordinal(o)):
            h = ((h ^ (v & MASK)) * PRIME) & MASK
    # -2**63 has no negated-literal spelling; it never occurs, and is refused
    # here rather than written wrong if it ever did.
    assert h != 1 << 63, "year %d folds to -2**63" % y
    return y, lo - EPOCH, hi - lo + 1, (h - (1 << 64) if h >> 63 else h)


def write(path):
    assert (datetime.MINYEAR, datetime.MAXYEAR) == (1, 9999), \
        "this corpus and its member assume datetime's range is 1 ... 9999"
    years = range(datetime.MINYEAR, datetime.MAXYEAR + 1)
    rows = ["    OracleYear{ year: %4di64, first: %8di64, days: %3di64, digest: %20di64 }"
            % year_row(y) for y in years]
    text = HEADER.replace("{count}", str(len(rows))) + ",\n".join(rows) + "\n];\n"
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote %s: %d years, %d bytes" % (path, len(rows), len(text.encode("utf-8"))))


def show(y):
    """Python's nine fields for every day of year y, one line per day, in the
    format the member prints for a year that disagrees."""
    lo = datetime.date(y, 1, 1).toordinal()
    hi = datetime.date(y, 12, 31).toordinal()
    for o in range(lo, hi + 1):
        print(" ".join(str(v) for v in fields(datetime.date.fromordinal(o))))


def main(argv):
    if len(argv) == 2 and argv[0] == "--year":
        show(int(argv[1]))
        return 0
    if len(argv) == 1 and not argv[0].startswith("-"):
        write(argv[0])
        return 0
    sys.stderr.write(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
